language: java
jdk:
- jdk8
script: mvn clean package -Dmaven.test.skip=true
branches:
  only:
  - master
notifications:
  email:
  - 553569682@qq.com
before_install:
- openssl aes-256-cbc -K $encrypted_ab82f6459cd0_key -iv $encrypted_ab82f6459cd0_iv
  -in travis.enc -out ~/.ssh/travis -d
- chmod 600 ~/.ssh/travis
- echo -e "Host 139.196.141.0\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- rsync -rv --delete -e 'ssh -o stricthostkeychecking=no' /home/travis/build/luohaoGit/my/target/xoxo.jar root@139.196.141.0:/usr/local/xoxo-jar
